# Crash Data

The dataset that I decided to choose was the crash dataset. I feel that is important to note, however, that this dataset also includes deaths and injuries that are caused by vehicles. In a good neighborhood there would be fewer deaths, injuries, and crashes overall.

In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
township_data = pd.read_csv('township-key.csv')
township_data

     Code                    Policy Agency
0    2101                 Baldwin Township
1    2102                 Collier Township
2    2103                 Cresent Township
3    2104               East Deer Township
4    2105               Elizabeth Township
..    ...                              ...
121  2506         University Of Pittsburgh
122  2507           Chatham College Police
123  2508              Duquesne University
124  2509         Robert Morris University
125  2601   Allegheny County Sheriffs Dept

[126 rows x 2 columns]

In [3]:
crash_data = pd.read_csv('crash-data-cumulative.csv')
crash_data

/opt/tljh/user/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (19,20,73,77,78,79,80,81,82,83,84,183,189) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,CRASH_CRN,DISTRICT,CRASH_COUNTY,MUNICIPALITY,POLICE_AGCY,CRASH_YEAR,CRASH_MONTH,DAY_OF_WEEK,TIME_OF_DAY,HOUR_OF_DAY,...,LANE_COUNT,RDWY_ORIENT,ROAD_OWNER,ROUTE,SPEED_LIMIT,SEGMENT,OFFSET,STREET_NAME,TOT_INJ_COUNT,SCHOOL_BUS_UNIT
0,2004000001,11,2,2454,02454,2004,1,5,257.0,2.0,...,2.0,E,2.0,2032,35.0,10.0,1000.0,LEWIS RUN RD,NaN,NaN
1,2004000010,11,2,2440,02440,2004,1,5,1027.0,10.0,...,2.0,W,3.0,NaN,35.0,NaN,NaN,COAL VALLEY RD,NaN,NaN
2,2004000016,11,2,2203,02203,2004,1,5,1839.0,18.0,...,2.0,W,2.0,3082,35.0,NaN,NaN,CLINTON FRANKFORT RD,NaN,NaN
3,2004000022,11,2,2404,02404,2004,1,6,914.0,9.0,...,2.0,N,4.0,NaN,25.0,NaN,NaN,NORTH BALPH AV,NaN,NaN
4,2004000030,11,2,2419,02419,2004,1,5,2230.0,22.0,...,2.0,S,4.0,NaN,20.0,NaN,NaN,THORNBERRY DR,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204893,2021017633,11,2,2116,02116,2020,10,7,1845.0,18.0,...,2.0,S,2.0,4003,45.0,17.0,2022.0,MCKNIGHT RD,1.0,NaN
204894,2021018779,11,2,2464,00000,2020,12,6,630.0,6.0,...,2.0,N,2.0,28,65.0,374.0,3802.0,ALLEGHENY VALLEY EX,0.0,NaN
204895,2021019758,11,2,2301,02301,2020,12,4,1245.0,12.0,...,2.0,S,4.0,NaN,25.0,NaN,NaN,SENECA ST,1.0,NaN
204896,2021021042,11,2,2301,02301,2020,11,3,1830.0,18.0,...,2.0,N,4.0,NaN,25.0,NaN,NaN,FORD ST,0.0,NaN
204897,2021021504,11,2,2301,68B03,2020,12,2,614.0,6.0,...,2.0,E,1.0,376,55.0,760.0,2477.0,PENN LINCOLN PY,1.0,NaN

In [6]:
crash_data['MUNICIPALITY'].min()

2101

In [5]:
township_data['Policy Agency']

0                     Baldwin Township
1                     Collier Township
2                     Cresent Township
3                   East Deer Township
4                   Elizabeth Township
                    ...
121           University Of Pittsburgh
122             Chatham College Police
123                Duquesne University
124           Robert Morris University
125     Allegheny County Sheriffs Dept
Name: Policy Agency, Length: 126, dtype: object

In [12]:
for index, row in crash_data.iterrows():
    for index, row_two in township_data.iterrows():
        if row[3] == row_two[0]:
            row[3] = row_two[1]
            break
crash_data.head()

KeyboardInterrupt: